CREATE TABLE `ms_user` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `NAME` varchar(12) CHARACTER SET utf8 DEFAULT NULL COMMENT '姓名（昵称）',
  `MOBILEPHONE` varchar(11) CHARACTER SET utf8 DEFAULT NULL COMMENT '移动电话',
  `PASSWORD` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '密码',
  `SEX` tinyint(4) DEFAULT '2' COMMENT '性别 （枚举）0男、1女、2未填写',
  `STATUS` tinyint(4) DEFAULT NULL COMMENT '用户状态（枚举）0 正常 、1 冻结',
  `CREATEDT` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='运营管理系统用户表';

CREATE TABLE `ms_data_auth` (
  `ID` bigint(20) NOT NULL,
  `MASTER_TYPE` tinyint(4) DEFAULT NULL COMMENT '主体类型：0:role; 1:user;',
  `MASTER_VAL` bigint(20) DEFAULT NULL COMMENT '主体值',
  `OPER_TABLE` varchar(45) COLLATE utf8_bin DEFAULT NULL COMMENT '数据权限操作对象表名',
  `SQL_STATMENT` varchar(300) COLLATE utf8_bin DEFAULT NULL COMMENT 'SQL表达式',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC COMMENT='数据权限';

CREATE TABLE `ms_permission` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `NAME` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '权限名称',
  `ENCODING` varchar(45) COLLATE utf8_bin DEFAULT NULL COMMENT '权限编码',
  `TYPE` tinyint(4) DEFAULT NULL COMMENT '权限类型：0:菜单权限; 1:页面元素权限;',
  `DESC` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '描述',
  `PARENT_ID` bigint(20) DEFAULT NULL COMMENT '父节点Id',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC COMMENT='运营平台 权限表';

CREATE TABLE `ms_permission_resource` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `PERMISSION_ID` bigint(20) DEFAULT NULL COMMENT '权限表id',
  `RESOURCE_ID` bigint(20) DEFAULT NULL COMMENT '资源表id',
  `PERMISSION_RELATION` varchar(4) COLLATE utf8_bin DEFAULT NULL COMMENT '同一个resource下 permission之间的关系 （and; or;）（null默认为and）',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=58 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC COMMENT='运营平台  权限和资源关联表';

CREATE TABLE `ms_resource` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) COLLATE utf8_bin DEFAULT NULL COMMENT '名称',
  `TYPE` tinyint(4) DEFAULT NULL COMMENT '类型: 0:url; ',
  `URL` varchar(45) COLLATE utf8_bin DEFAULT NULL COMMENT 'URL地址',
  `REQUEST` varchar(9) COLLATE utf8_bin DEFAULT NULL COMMENT '请求方法：GET POST PUT DELETE',
  `DESC` varchar(45) COLLATE utf8_bin DEFAULT NULL COMMENT '描述',
  `MODULE` varchar(45) COLLATE utf8_bin DEFAULT NULL COMMENT '所属模块',
  `NEED_AUTH` tinyint(4) DEFAULT NULL COMMENT '是否需要鉴权 0:否; 1:是;',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC COMMENT='运营后台资源表';

CREATE TABLE `ms_role` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `NAME` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '角色名称',
  `DESC` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '描述',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='运营平台角色表';

CREATE TABLE `ms_role_permission` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `ROLE_ID` bigint(20) DEFAULT NULL COMMENT '角色表id',
  `PERMISSION_ID` bigint(20) DEFAULT NULL COMMENT '权限表id',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC COMMENT='运营平台  角色和权限关联表';

CREATE TABLE `ms_user_role` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `USER_ID` bigint(20) DEFAULT NULL COMMENT '用户表id',
  `ROLE_ID` bigint(20) DEFAULT NULL COMMENT '角色表id',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC COMMENT='运营平台 用户和角色关联表';